# Generated by Django 5.2.6 on 2025-10-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30)),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('imageUrl', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('isActive', models.BooleanField()),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
    ]
